version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stakemetrics
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dev_secret_token_placeholder
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: dev_secret_token_placeholder
      MYSQL_DATABASE: stakemetrics
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge