# Base
api.security.token.secret=${API_SECURITY_TOKEN_SECRET}
app.frontend.base.url=${APP_FRONTEND_BASE_URL:https://stakemetrics.net}
app.backend.queue.base.url=${APP_BACKEND_QUEUE_BASE_URL}
service.api.key=${SERVICE_API_KEY}

# Admin
admin.master.key=${ADMIN_MASTER_KEY}

# GCP
app.gcp.location.id=${GCP_LOCATION_ID:us-central1}
app.gcp.project.id=${GCP_PROJECT_ID}

# Database
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=validate

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}

# Integrations
bets.api.token=${BETS_API_TOKEN}

# AutoBettor Webhook
autobettor.webhook.url=${AUTOBETTOR_WEBHOOK_URL:}
autobettor.webhook.token=${AUTOBETTOR_WEBHOOK_TOKEN:}

# Stripe
stripe.pricing.table=${STRIPE_PRICING_TABLE}
stripe.dark.mode.pricing.table=${STRIPE_DARK_MODE_PRICING_TABLE}
stripe.api.key=${STRIPE_API_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}

# Brevo
brevo.api.key=${BREVO_API_KEY}
app.mail.sender=${APP_MAIL_SENDER:support@stakemetrics.net}

# Telegram
telegram.api.id=${TELEGRAM_API_ID}
telegram.api.hash=${TELEGRAM_API_HASH}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
