app.frontend.base.url=http://stakemetrics.net
app.backend.queue.base.url=https://stake-metrics-be-h6jvewnsna-uc.a.run.app
app.gcp.project.id=stake-metrics-433620
app.gcp.location.id=us-central1
spring.datasource.url=jdbc:mysql://stake-metrics.cxw4gm4syqjl.us-east-2.rds.amazonaws.com:3306/stakemetrics
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
service.api.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGlhZ28gT3JuZWxhcyJ9.L1IC-jLLaNI-EMjA8iHDqF9vYi0WXBo5KMaSoDppA8M
spring.datasource.password=UIBmIuZ_BvwA
api.security.token.secret=UIBmIuZ_BvwA
stripe.pricing.table=prctbl_1PsBwLEvrQ7zPy18y7RN7QY2
stripe.dark.mode.pricing.table=prctbl_1PsByTEvrQ7zPy18NJSq0H8P
stripe.api.key=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
stripe.public.key=pk_live_51PVffeEvrQ7zPy184HM9ykmeqxN5j2rRXflBK9grjTt79GF7MpSd0iLAosJHC6djOfM8qEIzmhbNKz56Pqzcgywu00SAdITzbr
mailersend.domain.email=MS_ngBPn6@stakemetrics.net
mailersend.api.key=mlsn.fd33e711330503bcf6642f68223010483e122825299c6d1834dd988961a667cd
telegram.api.id=21770625
telegram.api.hash=5d6c78524953731cd978db89c7eb6230
bets.api.token=176456-TFL5dSmiPoyS8M
telegram.bot.token=6875098813:AAEmMj7BWA8gfEjXPpSvflcWpYXoiEO5RSE
logging.level.org.springframework.security=DEBUG