#Base
api.security.token.secret=dev_secret_token_placeholder
app.frontend.base.url=https://stakemetrics.net
app.backend.queue.base.url=https://stakemetrics.koyeb.app
service.api.key=service-jwt-placeholder-token

#Admin
admin.master.key=dev_secret_token_placeholder

#GCP
app.gcp.location.id=us-central1
app.gcp.project.id=stakemetrics-project

#Database
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.password=dev_secret_token_placeholder
spring.datasource.url=jdbc:mysql://rds-mysql-host.example.com:3306/stakemetrics

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.url=jdbc:mysql://rds-mysql-host.example.com:3306/stakemetrics
spring.flyway.user=root
spring.flyway.password=dev_secret_token_placeholder

#Integrations
bets.api.token=dummy_bets_api_token

autobettor.webhook.token=dummy_autobettor_token

stripe.pricing.table=prctbl_placeholder_5
stripe.dark.mode.pricing.table=prctbl_placeholder_6
stripe.api.key=sk_live_placeholder
stripe.public.key=pk_live_placeholder

brevo.api.key=dummy_brevo_api_key

telegram.api.id=21770625
telegram.api.hash=dummy_telegram_api_hash
telegram.bot.token=dummy_telegram_bot_token
