app.frontend.base.url=http://localhost:3000
app.backend.base.url=http://localhost:8080
spring.datasource.url=jdbc:mysql://localhost:3306/stake-metrics
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.datasource.password=UIBmIuZ_BvwA
api.security.token.secret=UIBmIuZ_BvwA
service.password=UIBmIuZ_BvwA
stripe.pricing.table=prctbl_1PWjTiEvrQ7zPy18hlKtUjPW
stripe.api.key=sk_test_51PVffeEvrQ7zPy18P0Y5XYNFChQjZxe7iIz5kXSvl4ni8OMNNk95KMb7EmR9WE17pH6Z6aOxPgrGFkPnThiDPcW700q4GU4Jnm
stripe.public.key=pk_test_51PVffeEvrQ7zPy18W30s4uVxV8VtlxQgW9aASPu0vNt7BdNdsHnzaoIcIf28FEuHGP4dLkqOj4Lmb3SKAhIYUZpr00BxGWItEs
mailersend.domain.email=MS_BCyJGD@trial-k68zxl28en5lj905.mlsender.net
mailersend.api.key=mlsn.3b6c3b8576ffbd80bb9ff4b7fcccb5a1bcd5dfa3ed53f2be9cd623babd4bc859
telegram.api.id=21770625
telegram.api.hash=5d6c78524953731cd978db89c7eb6230
telegram.bot.token=6875098813:AAEmMj7BWA8gfEjXPpSvflcWpYXoiEO5RSE
logging.level.org.springframework.security=DEBUG